Update validate-mpackage.yml

diff --git a/.github/workflows/validate-mpackage.yml b/.github/workflows/validate-mpackage.yml
--- a/.github/workflows/validate-mpackage.yml
+++ b/.github/workflows/validate-mpackage.yml
@@ -120,6 +120,18 @@ jobs:
           exit 1
         fi
 
+    - name: Check for malicious content
+      if: steps.skip-if-deleted.outputs.skip != 'true'
+      id: check-malicious-content
+      run: |
+        FILE="${{ steps.check-file-count.outputs.FILE }}"
+        if grep -q -R -E 'os\.exec|lfs\.rmdir|sysDataSendRequest' unzipped_package/
+          echo "Pass: security checks"
+        else
+          echo "Error: questionable functions or events used, please validate manually"
+          exit 1
+        fi
+
     - name: Extract package name and author, check for duplicates
       if: steps.skip-if-deleted.outputs.skip != 'true'
       id: check-package-name
